### ISSUE TITLE
NPC's trigger join/leave

### ISSUE THREAD

**Issue by AverageFemale** [811Alex/NotifMod#7] opened 2022-09-03 20:19 UTC
1.19.2

When an NPC loads and unloads from the playerlist it causes the the mod to trigger the player.join and player.leave notifications. I've only tested this with the Citizens NPC plugin. I don't know if this happens for any others.

**Comment by 811Alex** [comment] 2022-09-04 22:13
Thanks for reporting it! I confirmed it, just didn't cross my mind to test with a plugin like that and it makes sense it does that, due to how it works.
I wanna try and find a solution that would ideally not drop support for offline-mode servers or LAN servers (for these notifications), so I'll need to look into it a bit further when I have a bit of time.

**Comment by Kweeme** [comment] 2022-09-05 06:48
Alrighty, do whatever you need to do.

**Comment by Kweeme** [comment] 2022-10-19 17:11
Is this mod still being maintained?

**Comment by 811Alex** [comment] 2022-12-01 22:21
I don't see a reason to close this as either atm.

**Comment by Xampa5** [comment] 2023-11-09 21:10
Similar issue: Any update of Styled Player List triggers player.join. 
And this mod has settings to refresh every X ticks and/or every chat messages (in order to update player name color, [Prefix] and so on), so it's unbearable to have join notification enabled on servers using it.

**Closed** 2023-11-12 01:43 UTC
Labels: bug

**Comment by 811Alex** [comment] 2023-11-12 02:21
OK, so I did a couple of things to combat this issue.
**Try the latest version and let me know if it's still a problem!**

This commit *should* also fix @Xampa5's issue, but that one was happening for a different reason, so if that's still a problem, it might be best to make a separate issue.

Server mods that add NPCs that look like players basically tell clients the NPC is a player, so it's kinda hard to distinguish between them client-side. I tested with a few server mods/plugins, but there's a chance there's one out there that could still cause issues. If someone finds one, feel free to make an issue and include the mod/plugin name and any other info you may have.
